version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: domeo_doors
      POSTGRES_USER: domeo_user
      POSTGRES_PASSWORD: domeo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/yandex_cloud_schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U domeo_user -d domeo_doors"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Next.js приложение
  app:
    image: cr.yandex/crpvhe4bl478pkh29sem/domeo-doors:latest
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://domeo_user:domeo_password@postgres:5432/domeo_doors
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-min-32-chars
      - NEXT_PUBLIC_APP_URL=http://130.193.40.35
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data: